spring:
  application:
    name: backend

  profiles:
    active: dev

  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Europe/Madrid

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:mem:pocasluces
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        jdbc:
          time_zone: Europe/Madrid

  sql:
    init:
      mode: always

server:
  port: 8080

logging:
  level:
    com.pocasluces: DEBUG

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://localhost:5432/sevillasinluz
    driver-class-name: org.postgresql.Driver
    username: sevillasinluz_user
    password: sevillanos40SinLuces

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: Europe/Madrid

  sql:
    init:
      mode: never

server:
  port: 8081

logging:
  level:
    com.pocasluces: INFO
